### ISSUE TITLE
Error from command line

### ISSUE THREAD

**Issue by AgentMulder** [MaxGraey/WebGL2-TypeScript#2]
When I include WebGL2.d.ts on the command line, I get the following
error:

WebGL2.d.ts(93,11): error TS2430: Interface 'WebGL2RenderingContext'
incorrectly extends interface 'WebGLRenderingContext'.  Types of
property 'texImage2D' are incompatible.

tsc --version
3.1.6

**Comment by MaxGraey** [comment]
Hmm, it seems TypeScript updated WebGLRenderingContext definitions

**Comment by isral** [comment]
@MaxGraey 
I just installed VS Code and Typescript 3.7.5 and there are several errors.
All declare var produce error because of mismatch type.

**Comment by MaxGraey** [comment]
latest TS already support [WebGL2RenderingContext](https://github.com/microsoft/TypeScript/blob/91ffa1c752ac26882b1426fb4c9012701c1d908e/lib/lib.webworker.d.ts#L3414)

And this repo will deprecated
